service: gratitude-jar

plugins:
    - serverless-s3-sync

custom:
    s3Bucket: app.sloikwdziecznosci.pl
    s3Sync:
        - bucketName: ${self:custom.s3Bucket}
          localDir: /app

provider:
    name: aws
    region: eu-central-1
    profile: personal

resources:
    Resources:
        ## Specifying the S3 Bucket
        WebAppS3Bucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.s3Bucket}
                AccessControl: PublicRead
                WebsiteConfiguration:
                    IndexDocument: index.html
        ## Specifying the policies
        WebAppS3BucketPolicy:
            Type: AWS::S3::BucketPolicy
            Properties:
                Bucket:
                    Ref: WebAppS3Bucket
                PolicyDocument:
                    Statement:
                        - Sid: PublicReadGetObject
                          Effect: Allow
                          Principal: "*"
                          Action:
                              - s3:GetObject
                          Resource: arn:aws:s3:::${self:custom.s3Bucket}/*
